[package]
name = "accounts"
version = "0.1.0"
authors = ["anton <tosha.fedotov.2000@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
diesel = { version = "1.4.4", features = ["postgres", "r2d2", "uuidv07"] }
dotenv = "0.15.0"
r2d2 = "0.8.9"
serde = "1"
uuid = { version = "0.8", features = ["serde"] }
