refresh_rate = "30 seconds"

[appenders.stdout]
kind = "console"
[appenders.requests]
kind = "file"
path = "log/requests.log"
[appenders.requests.encoder]
pattern = "{d} - {m}{n}"

[root]
level = "trace"
appenders = ["stdout"]
