version: "3.8"
services:
  api:
    entrypoint: ["carton", "exec", "morbo"]
    command: ["./script/doojon"]
    volumes:
      - "./doojon:/usr/src/app"
    ports:
      - "2000:3000"
  db:
    environment:
      - "POSTGRES_DATABASE=doojon"
      - "POSTGRES_USER=doojon"
      - "POSTGRES_PASSWORD=password"
    ports:
      - "5432:5432"
  proxy:
    volumes:
      - "./nginx.override.conf:/etc/nginx/nginx.conf"
    ports:
      - "1999:80"
