requires 'Bread::Board';
requires 'Future::AsyncAwait';
requires 'Mojo::Pg';
requires 'Mojolicious';
requires 'OpenAPI::Generator';
requires 'Redis';
requires 'YAML::XS';
requires 'perl', '>=', '5.30';

on develop => sub {
  requires 'DDP';
};
