requires 'Bread::Board';
requires 'Future::AsyncAwait';
requires 'Module::Find';
requires 'Mojo::Pg';
requires 'Mojolicious';
requires 'Moose';
requires 'Redis';
requires 'perl', '>=', '5.30';

on develop => sub {
  requires 'DDP';
};
