openapi: 3.0.3
info:
  title: openapi for doojon.com
  version: 0.0.1

paths:
  /api/resource/challenges:
    post:
      tags: [resource_challenges]
      description: create-resource for challenges
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - descr
                - proposed_by
                - title
              properties:
                create_time:
                  type: string
                descr:
                  type: string
                id:
                  type: string
                proposed_by:
                  type: string
                title:
                  type: string
                update_time:
                  type: string
      responses:
        "200":
          description: id of created resource
          content:
            application/json:
              schema:
                type: object
                required: [id]
                properties:
                  id:
                    type: string
    get:
      tags: [resource_challenges]
      parameters:
        - name: id
          in: query
          schema:
            type: string
      responses:
        "200":
          description: fields of record of resource "challenges"
          content:
            application/json:
              schema:
                type: object
                required:
                  - create_time
                  - descr
                  - id
                  - proposed_by
                  - title
                  - update_time
                properties:
                  create_time:
                    type: string
                  descr:
                    type: string
                  id:
                    type: string
                  proposed_by:
                    type: string
                  title:
                    type: string
                  update_time:
                    type: string
    put:
      tags: [resource_challenges]
      parameters:
        - name: id
          in: query
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - descr
                - proposed_by
                - title
              properties:
                create_time:
                  type: string
                descr:
                  type: string
                id:
                  type: string
                proposed_by:
                  type: string
                title:
                  type: string
                update_time:
                  type: string
      responses:
        "200":
          description: id of the updated record
          content:
            application/json:
              schema:
                type: object
                required: [id]
                properties:
                  id:
                    type: string
    delete:
      tags: [resource_challenges]
      parameters:
        - name: id
          in: query
          schema:
            type: string
      responses:
        "200":
          description: id of the deleted record
          content:
            application/json:
              schema:
                type: object
                required: [id]
                properties:
                  id:
                    type: string
  /api/resource/post_comment_likes:
    post:
      tags: [resource_post_comment_likes]
      description: create-resource for post_comment_likes
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - comment_id
                - liked_by
              properties:
                comment_id:
                  type: string
                liked_by:
                  type: string
      responses:
        "200":
          description: prints "1" as a sign of success
          content:
            application/json:
              schema:
                enum: [1]
  /api/resource/post_comments:
    post:
      tags: [resource_post_comments]
      description: create-resource for post_comments
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - message
                - post_id
                - writed_by
              properties:
                create_time:
                  type: string
                id:
                  type: string
                message:
                  type: string
                post_id:
                  type: string
                writed_by:
                  type: string
      responses:
        "200":
          description: id of created resource
          content:
            application/json:
              schema:
                type: object
                required: [id]
                properties:
                  id:
                    type: string
    get:
      tags: [resource_post_comments]
      parameters:
        - name: id
          in: query
          schema:
            type: string
      responses:
        "200":
          description: fields of record of resource "post_comments"
          content:
            application/json:
              schema:
                type: object
                required:
                  - create_time
                  - id
                  - message
                  - post_id
                  - writed_by
                properties:
                  create_time:
                    type: string
                  id:
                    type: string
                  message:
                    type: string
                  post_id:
                    type: string
                  writed_by:
                    type: string
    put:
      tags: [resource_post_comments]
      parameters:
        - name: id
          in: query
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - message
                - post_id
                - writed_by
              properties:
                create_time:
                  type: string
                id:
                  type: string
                message:
                  type: string
                post_id:
                  type: string
                writed_by:
                  type: string
      responses:
        "200":
          description: id of the updated record
          content:
            application/json:
              schema:
                type: object
                required: [id]
                properties:
                  id:
                    type: string
    delete:
      tags: [resource_post_comments]
      parameters:
        - name: id
          in: query
          schema:
            type: string
      responses:
        "200":
          description: id of the deleted record
          content:
            application/json:
              schema:
                type: object
                required: [id]
                properties:
                  id:
                    type: string
  /api/resource/post_likes:
    post:
      tags: [resource_post_likes]
      description: create-resource for post_likes
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - liked_by
                - post_id
              properties:
                liked_by:
                  type: string
                post_id:
                  type: string
      responses:
        "200":
          description: prints "1" as a sign of success
          content:
            application/json:
              schema:
                enum: [1]
  /api/resource/posts:
    post:
      tags: [resource_posts]
      description: create-resource for posts
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - body
                - challenge_id
                - title
                - writed_by
              properties:
                body:
                  type: string
                challenge_id:
                  type: string
                create_time:
                  type: string
                id:
                  type: string
                title:
                  type: string
                writed_by:
                  type: string
      responses:
        "200":
          description: id of created resource
          content:
            application/json:
              schema:
                type: object
                required: [id]
                properties:
                  id:
                    type: string
    get:
      tags: [resource_posts]
      parameters:
        - name: id
          in: query
          schema:
            type: string
      responses:
        "200":
          description: fields of record of resource "posts"
          content:
            application/json:
              schema:
                type: object
                required:
                  - body
                  - challenge_id
                  - create_time
                  - id
                  - title
                  - writed_by
                properties:
                  body:
                    type: string
                  challenge_id:
                    type: string
                  create_time:
                    type: string
                  id:
                    type: string
                  title:
                    type: string
                  writed_by:
                    type: string
    put:
      tags: [resource_posts]
      parameters:
        - name: id
          in: query
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - body
                - challenge_id
                - title
                - writed_by
              properties:
                body:
                  type: string
                challenge_id:
                  type: string
                create_time:
                  type: string
                id:
                  type: string
                title:
                  type: string
                writed_by:
                  type: string
      responses:
        "200":
          description: id of the updated record
          content:
            application/json:
              schema:
                type: object
                required: [id]
                properties:
                  id:
                    type: string
    delete:
      tags: [resource_posts]
      parameters:
        - name: id
          in: query
          schema:
            type: string
      responses:
        "200":
          description: id of the deleted record
          content:
            application/json:
              schema:
                type: object
                required: [id]
                properties:
                  id:
                    type: string
  /api/resource/profiles:
    post:
      tags: [resource_profiles]
      description: create-resource for profiles
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - id
                - reg_date
                - username
              properties:
                id:
                  type: string
                reg_date:
                  type: string
                username:
                  type: string
      responses:
        "200":
          description: id of created resource
          content:
            application/json:
              schema:
                type: object
                required: [id]
                properties:
                  id:
                    type: string
    get:
      tags: [resource_profiles]
      parameters:
        - name: id
          in: query
          schema:
            type: string
      responses:
        "200":
          description: fields of record of resource "profiles"
          content:
            application/json:
              schema:
                type: object
                required:
                  - id
                  - reg_date
                  - username
                properties:
                  id:
                    type: string
                  reg_date:
                    type: string
                  username:
                    type: string
    put:
      tags: [resource_profiles]
      parameters:
        - name: id
          in: query
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - id
                - reg_date
                - username
              properties:
                id:
                  type: string
                reg_date:
                  type: string
                username:
                  type: string
      responses:
        "200":
          description: id of the updated record
          content:
            application/json:
              schema:
                type: object
                required: [id]
                properties:
                  id:
                    type: string
    delete:
      tags: [resource_profiles]
      parameters:
        - name: id
          in: query
          schema:
            type: string
      responses:
        "200":
          description: id of the deleted record
          content:
            application/json:
              schema:
                type: object
                required: [id]
                properties:
                  id:
                    type: string



