version: '3'

services:
  doojon:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 16
        USER_UID: 1000
        USER_GID: 1000
    volumes:
      - ../..:/workspace:cached
    command: sleep infinity
    environment:
      CLOUD_SPANNER_EMULATOR: doojon_db:9010
  doojon_db:
    image: gcr.io/cloud-spanner-emulator/emulator
    restart: unless-stopped
volumes:
  doojon-data:
  accounts-data:
networks:
  default:
    name: doojondev
