apiVersion: v1
kind: ReplicationController
metadata:
  name: rc.accounts
  namespace: doojon
spec:
  replicas: 1
  selector:
    app: accounts
  template:
    metadata:
      name: accounts
      labels:
        app: accounts
    spec:
      containers:
        - name: accounts
          image: doojonio/accounts
          ports:
            - containerPort: 3000
