- name: make sure dnf-plugins-core installed
  dnf:
    name: dnf-plugins-core
    state: present
- name: install docker repository
  command:
    cmd: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
    warn: false
- name: delete deprecated dockers if exists
  dnf:
    name:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-selinux
      - docker-engine-selinux
      - docker-engine
    state: absent
- name: install docker
  dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
- name: enable docker service
  systemd:
    name: docker
    enabled: true
    state: started