apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts-deployment
  labels:
    app: accounts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounts
  template:
    metadata:
      labels:
        app: accounts
    spec:
      serviceAccountName: doojon
      containers:
        - name: accounts
          image: doojonio/accounts
          #resources:
          #  limits:
          #    memory: "100Mi"
          #    cpu: "60m"
          ports:
            - containerPort: 8080
              name: http
          livenessProbe:
            httpGet:
              path: /api/svc/accounts/1/health
              port: 8080
            initialDelaySeconds: 2
          readinessProbe:
            httpGet:
              path: /api/svc/accounts/1/health
              port: 8080
          volumeMounts:
            - mountPath: "/usr/src/app/Accounts.toml"
              subPath: "Accounts.toml"
              name: config
              readOnly: true
        - name: cloud-sql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.17
          command:
            - "/cloud_sql_proxy"
            - "-instances=doojon-test:europe-central2:testdb=tcp:5432"
            - "-credential_file=/secrets/service_account.json"
          securityContext:
            runAsNonRoot: true
          resources:
            limits:
              cpu: "60m"
              memory: "100Mi"
          volumeMounts:
            - mountPath: /secrets
              name: doojon-sa-secret
              readOnly: true
      volumes:
        - name: doojon-sa-secret
          secret:
            secretName: doojon-sa-secret
        - name: config
          configMap:
            name: accounts-config
