apiVersion: apps/v1
kind: Deployment
metadata:
  name: doojon-deployment
  labels:
    app: doojon
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: doojon
  template:
    metadata:
      labels:
        app: doojon
    spec:
      serviceAccountName: doojon
      containers:
        - name: doojon
          image: doojonio/doojon
          #resources:
          #  limits:
          #    memory: "100Mi"
          #    cpu: "60m"
          env:
            - name: DOOJON_RUN_DB_MIGRATIONS
              value: "1"
          ports:
            - containerPort: 8080
              name: http
          livenessProbe:
            httpGet:
              path: /api/svc/doojon/1/health
              port: 8080
            initialDelaySeconds: 2
          readinessProbe:
            httpGet:
              path: /api/svc/doojon/1/health
              port: 8080
            initialDelaySeconds: 2
          volumeMounts:
            - mountPath: "/usr/src/app/doojon.json"
              subPath: "doojon.json"
              name: config
              readOnly: true
        - name: cloud-sql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.17
          command:
            - "/cloud_sql_proxy"
            - "-instances=doojon-test:europe-central2:testdb=tcp:5432"
            - "-credential_file=/secrets/service_account.json"
          securityContext:
            runAsNonRoot: true
          resources:
            limits:
              memory: "100Mi"
              cpu: "60m"
          volumeMounts:
            - mountPath: /secrets
              name: doojon-sa-secret
              readOnly: true
      volumes:
        - name: doojon-sa-secret
          secret:
            secretName: doojon-sa-secret
        - name: config
          configMap:
            name: doojon-config
