- name: ensure openshift
  pip:
    name: openshift
    state: present
- name: ensure k8s namespace
  k8s:
    name: doojon
    api_version: v1
    kind: Namespace
    state: present

- name: ensure k8s definitons synced
  copy:
    src: files/k8s
    dest: /home/{{ k8s_user }}/

- name: ensure k8s objects present
  k8s:
    src: /home/{{ k8s_user }}/k8s/{{ item }}.yml
  with_items:
    - rc.accounts
