version: "3"
services:
  doojonf:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        - VARIANT=latest
    command: sleep infinity
    volumes:
      - ../../../:/workspace/
volumes:
  accounts-data:
  doojon-data:

networks:
  default:
    external: yes
    name: doojondev
