name: accounts ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repository
        uses: actions/checkout@v2
      - name: build and push accounts image
        uses: docker/build-push-action@v2
        with:
          context: ./accounts
          file: ./accounts/dockerfile
          push: true
          tags: |
            doojonio/doojon-accounts:latest
            doojonio/doojon-accounts:latest-dev
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
