name: Check Doojon

on:
  push:
    branches: [ main ]
    paths: ["services/doojon/**"]
  pull_request:
    branches: [ main ]
    paths: ["services/doojon/**"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      working-directory: "services/doojon"
      run: |
        npm ci

    - name: Style Check
      working-directory: "services/doojon"
      run: |
        npm run style-check

    - name: Test
      working-directory: "services/doojon"
      env:
        GCP_PROJECT: test
        SPANNER_EMULATOR_HOST: test:123
        SPANNER_INSTANCE: test
        SPANNER_DATABASE: test
      run: |
        npm run test
