name: Check Doojon

on:
  push:
    branches: [ main ]
    paths:
      - "services/doojon/**"
      - ".github/workflows/*doojon*"

  pull_request:
    branches: [ main ]
    paths: ["services/doojon/**"]

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:16
    services:
      redis:
        image: redis

    steps:
    - uses: actions/checkout@v2

    - name: Build
      working-directory: "services/doojon"
      run: |
        npm ci

    - name: Style Check
      working-directory: "services/doojon"
      run: |
        npm run style-check

    - name: Test
      working-directory: "services/doojon"
      env:
        GCP_PROJECT: test
        SPANNER_EMULATOR_HOST: test:123
        SPANNER_INSTANCE: test
        SPANNER_DATABASE: test
        REDIS_URL: redis://redis
      run: |
        npm run test
