name: doojon ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repository
        uses: actions/checkout@v2
      - name: build and push doojon image
        uses: docker/build-push-action@v2
        with:
          context: ./doojon
          file: ./doojon/dockerfile
          push: true
          tags: |
            doojonio/doojon/doojon:latest
            doojonio/doojon/doojon:latest-dev
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
