name: doojonf ci

on:
  push:
    branches: [ master ]
    paths:
      - doojonf/**
      - dockerfiles/doojonf.Dockerfile
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repository
        uses: actions/checkout@v2
      - name: install node
        uses: actions/setup-node@v1
        with:
          node-version: '16'
      - name: build dist
        working-directory: './doojonf'
        run: |
          npm ci
          npx ng build --prod
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v1
      - name: login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_KEY }}
      - name: build and push doojonf image
        uses: docker/build-push-action@v2
        with:
          context: ./doojonf
          file: ./dockerfiles/doojonf.Dockerfile
          push: true
          tags: |
            ${{ github.repository_owner }}/doojonf:latest
