name: doojon ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repository
        uses: actions/checkout@v2
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v1
      - name: login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build and push doojon image
        uses: docker/build-push-action@v2
        with:
          context: ./doojon
          file: ./doojon/dockerfile
          push: true
          tags: |
            ghcr.io/doojonio/doojon:latest
            ghcr.io/doojonio/doojon:latest-dev
