name: doojon ci

on:
  push:
    branches: [ master ]
    paths:
      - doojon/**
      - dockerfiles/doojon.Dockerfile

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repository
        uses: actions/checkout@v2
      - name: set up docker build
        uses: docker/setup-buildx-action@v1
      - name: login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_KEY }}
      - name: build and push doojon image
        uses: docker/build-push-action@v2
        with:
          context: ./doojon
          file: ./dockerfiles/doojon.Dockerfile
          push: true
          tags: |
            ${{ github.repository_owner }}/doojon:latest
